# Generated by Django 5.0.3 on 2024-03-23 13:34

import accountman.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogsite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pictures/user_pfp.png', upload_to=accountman.models.random_pfp)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_blog_comments', models.ManyToManyField(blank=True, related_name='user_blog_comments', to='blogsite.comment')),
                ('user_blog_likes', models.ManyToManyField(blank=True, related_name='user_blog_likes', to='blogsite.blogpost')),
                ('user_blog_posts', models.ManyToManyField(blank=True, related_name='user_blog_posts', to='blogsite.blogpost')),
            ],
        ),
    ]
