# Generated by Django 5.0.3 on 2024-05-01 16:47

import blogsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(upload_to=blogsite.models.blog_image_filename),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_image',
            field=models.ImageField(blank=True, upload_to=blogsite.models.blog_title_filename),
        ),
    ]
