# Generated by Django 4.2.1 on 2023-05-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend_requests',
            new_name='incoming_friend_requests',
        ),
        migrations.AddField(
            model_name='friend',
            name='outgoing_friend_requests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
