# Generated by Django 4.2.2 on 2023-06-27 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendman', '0002_rename_friend_requests_friend_incoming_friend_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='incoming_friend_requests',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='outgoing_friend_requests',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.CreateModel(
            name='FriendRequestRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('incoming_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_friend', to=settings.AUTH_USER_MODEL)),
                ('outgoing_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_friend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to=settings.AUTH_USER_MODEL)),
                ('friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, default=list, to='friendman.friendrequestrelationship'),
        ),
        migrations.AddField(
            model_name='friend',
            name='friends',
            field=models.ManyToManyField(blank=True, default=list, to='friendman.friendrelationship'),
        ),
    ]
